---
# tasks file for python
- name: Install Python dependencies
  apt:
    name:
      - python3
      - python3-setuptools
      - python3-dev
      - build-essential
    state: present
    update_cache: yes
  become: yes

- name: Install PyMySQL
  apt:
    name: python3-pymysql
    state: present
  become: yes


